(Goto, None, None, 2)
(SetDim, 10, None, iga)
(=, "hola", , sls)
(Print, sls, \n, )
(Print, "hola mundo", \n, )
(=, 5.3, , dlc)
(+, dlc, 3, dlt1)
(=, dlt1, , ilb)
(+, ilb, dlc, dlt2)
(Print, dlt2, \n, )
(END, , , )
